### ISSUE TITLE
support firefox plugin "Ublock Origin"

### ISSUE THREAD

**Issue by DO1JLR** [re4jh/osm2marudor#3]
[UBLOCK origin](https://addons.mozilla.org/de/firefox/addon/ublock-origin/) blockiert irgend welche scripte, die da ausgefhrt werden und als potentielle Werbung eingestuft werden.

Ansicht mit aktivierten Ublock Origin:
![grafik](https://user-images.githubusercontent.com/16953664/73974383-8d825280-4924-11ea-8e7e-196bc4f0c18e.png)

Ansicht mit deaktivierten Ublock Origin:
![grafik](https://user-images.githubusercontent.com/16953664/73974697-1ac5a700-4925-11ea-89d1-ef03f5c7614f.png)

**Comment by wolf128058** [comment]
Pfff. Der scharfe Regexr aus diesen Gefilden stört sich daran, dass das File zur Geo-Suche unter geo.php rennt. ([marudor_cache/geo.php](https://github.com/re4jh/osm2marudor/blob/master/marudor_cache/geo.php)?...). Ich denke darüber nach, ob ich das deswegen renamen - oder du das deswegen whitelisten könntest.

**Comment by DO1JLR** [comment]
Ich kann das whitelisten. Hab ich auch schon gemacht.

Aber eventuell willst du ja für den nächsten mit Ublock Origin mindestens ein check einbauen der prüft ob es geladen werden kann und sonst eine fehlermeldung ausspuckt mit dem ein normalsterblicher user auf die idee kommen kann, ublock origin hier zu whitelisten
